language: node_js
node_js:
  - 12
script:
  - yarn build
  - cd test/ng9 && yarn && yarn test:ci
deploy:
  provider: script
  script: bash ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
