language: node_js
node_js:
  - 12
script:
  - yarn build
  - yarn build:doc
  - cd "${TRAVIS_BUILD_DIR}/test/ng10" && yarn && yarn test:ci
  - cd "${TRAVIS_BUILD_DIR}/test/ng9" && yarn && yarn test:ci
  - cd "${TRAVIS_BUILD_DIR}/test/ng8" && yarn && yarn test:ci
  - cd "${TRAVIS_BUILD_DIR}/test/ng7" && yarn && yarn test:ci
deploy:
  provider: script
  script: cd "${TRAVIS_BUILD_DIR}" && REPO_ROOT="${TRAVIS_BUILD_DIR}" ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
