language: node_js
node_js:
  - 12
script:
  - yarn build
  - cd "${TRAVIS_BUILD_DIR}/test/ng9" && yarn && yarn test:ci
  - cd "${TRAVIS_BUILD_DIR}/test/ng8" && yarn && yarn test:ci
  - cd "${TRAVIS_BUILD_DIR}/test/ng7" && yarn && yarn test:ci
deploy:
  provider: script
  script: cd "${TRAVIS_BUILD_DIR}" && ./ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
